### PR TITLE
Enable configfs-tsm interface

### PR DESCRIPTION
**Pull request by arvind5**

### CODE REVIEW

**Comment by JakubLedworowski** [comment]
Hi, what is preventing this commit from being merged?

**Comment by arvind5** [comment]
> Hi, what is preventing this commit from being merged?

we have implemented this change internally and will be pushed on next release sometime this week.

**Comment by fidencio** [comment]
> we have implemented this change internally and will be pushed on next release sometime this week.

Should be closed as part of the v1.5.0 release?

**Comment by arvind5** [comment]
> > we have implemented this change internally and will be pushed on next release sometime this week.
> 
> Should be closed as part of the v1.5.0 release?

yes, closed now, thanks!

**Pull request closed without merging**
